version: 1.0.{build}
branches:
  only:
  - main
image: Visual Studio 2022
build_script:
- ps: .\build_nuget.ps1
artifacts:
- path: Output\*.nupkg
  name: NugetPackages
deploy:
- provider: NuGet
  api_key:
    secure: y+7WZBzkjiCwo2zv0W+oQNGJ6sh10RdrirYgmnL9azcgk7n9Wmodjohy0IUKg1PT
  username:
    secure: 1K8aMtHh4cgJD51abewigQ==
  artifact: NugetPackages