version: 1.0.{build}
branches:
  only:
  - main
image: Visual Studio 2022
build_script:
- ps: .\build_nuget.ps1
artifacts:
- path: Output\*.nupkg
  name: NugetPackages
deploy:
- provider: NuGet
  api_key:
    secure: SpmYcFTtKxHbv/9755B2KPjhS0iuD/LQKvIVksFyFDV3TExX0vmhnp8rE8qA6fo+
  username:
    secure: 1K8aMtHh4cgJD51abewigQ==
  artifact: NugetPackages